### ISSUE TITLE
Correct method name to conform with Kotlin's naming convention

### ISSUE THREAD

**Issue by vittee** [Mie285/PrimeNumberProject#1]
https://github.com/Mie285/PrimeNumberProject/blob/7c0de14c2341f34f2f71d7c23fc259c23a94263c/src/Checking.kt#L2

https://github.com/Mie285/PrimeNumberProject/blob/7c0de14c2341f34f2f71d7c23fc259c23a94263c/src/CheckingPrimeNumber.kt#L8

## [Kotlin Naming Rules](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules)

**Comment by Mie285** [comment]
fun isPrimeNumbers() : Boolean

 override fun isPrimeNumbers(): Boolean {

**Comment by vittee** [comment]
Which commit?

**Comment by Mie285** [comment]
We delete all file please check line 1 - 3 in e30bfc7 and line 7 in 7645023
