### ISSUE TITLE
Un-meaningful interface name

### ISSUE THREAD

**Issue by vittee** [Mie285/PrimeNumberProject#2]
https://github.com/Mie285/PrimeNumberProject/blob/7c0de14c2341f34f2f71d7c23fc259c23a94263c/src/Checking.kt#L1

Be more specific.

**Comment by Mie285** [comment]
interface PrimeNumber{

**Comment by vittee** [comment]
Which commit?

**Comment by Mie285** [comment]
7c0de14 is deleted, please check Line 1 in e30bfc7
