### ISSUE TITLE
Method name should be a verb that denote an action.

### ISSUE THREAD

**Issue by vittee** [Mie285/PrimeNumberProject#3]
https://github.com/Mie285/PrimeNumberProject/blob/7c0de14c2341f34f2f71d7c23fc259c23a94263c/src/Numbers.kt#L2

**Comment by Mie285** [comment]
fun showingOutcome()

**Comment by vittee** [comment]
Which commit?

**Comment by Mie285** [comment]
Line 2 in 435cb40
