### ISSUE TITLE
Unnecessary class.

### ISSUE THREAD

**Issue by vittee** [Mie285/PrimeNumberProject#4]
https://github.com/Mie285/PrimeNumberProject/blob/7c0de14c2341f34f2f71d7c23fc259c23a94263c/src/PrimeNumberSet.kt#L1

Push this member down to the concrete class.
https://github.com/Mie285/PrimeNumberProject/blob/7c0de14c2341f34f2f71d7c23fc259c23a94263c/src/PrimeNumberSet.kt#L2

**Comment by Mie285** [comment]
This class is already delete.
