### ISSUE TITLE
Avoid using snake_case.

### ISSUE THREAD

**Issue by vittee** [Mie285/PrimeNumberProject#5]
Use [cameCase](https://en.wikipedia.org/wiki/Camel_case).

https://github.com/Mie285/PrimeNumberProject/blob/bbc190e9be7ed335ac98a7ff120584e4ca786787/src/Calculator.kt#L3

[Kotlin Naming Rules](https://kotlinlang.org/docs/reference/coding-conventions.html#naming-rules)

**Comment by Mie285** [comment]
val setOfNumbers = listOf(

**Comment by vittee** [comment]
Which commit?

**Comment by Mie285** [comment]
Line 3 in 1fa1796
