### ISSUE TITLE
Unclear property value's origin

### ISSUE THREAD

**Issue by vittee** [Mie285/PrimeNumberProject#6]
https://github.com/Mie285/PrimeNumberProject/blob/c44a98290da8aba985ac0fe6d95b02a8835b0d7c/src/PrimeNumberSet.kt#L7

How any why is this property set to true without proper determination?

**Comment by Mie285** [comment]
var primeNumbers : Boolean = false

**Comment by vittee** [comment]
Which commit?

**Comment by Mie285** [comment]
Line 7 in 7c0de14

**Comment by vittee** [comment]
Just by changing this field's value using literal boolean value does not make it more useful.

**Comment by Mie285** [comment]
We already implement checking prime number logic : Line 7 - 14 on 3032c6e
